import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="antialiased min-h-screen grid grid-rows-[auto_1fr_auto]">
        <Header />
        <main className="max-w-[1224px] mx-auto w-full ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
